CC=g++
CFLAGS=-c -Wall

all: proxy

proxy: server.c
	$(CC) $(CFLAGS) -o proxy_parse.o -c proxy_parse.c -lpthread
	$(CC) $(CFLAGS) -o proxy.o -c proxy_server.c -lpthread
	$(CC) $(CFLAGS) -o proxy proxy_parse.o parse.o -lpthread

clean:
	rm -f proxy *.o

#tar:
   # tar -cvzf ass1.tgz proxy_server.c README Makefile proxy_parse.c parse.h